export default function TermsPage() {
  return (
    <div className="min-h-screen pt-24 pb-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-brand-gray-500 text-sm mb-8">Last updated: April 2026</p>

        <div className="prose prose-invert max-w-none space-y-6 text-brand-gray-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white">1. Service Description</h2>
            <p>
              JargonScan provides AI-powered consumer document analysis. We scan uploaded documents
              to identify potential errors, overcharges, and violations based on publicly available
              consumer protection laws and regulations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">2. Not Legal Advice</h2>
            <p>
              JargonScan is NOT a law firm and does NOT provide legal advice or legal representation.
              All findings, flags, and recommendations generated by JargonScan are for informational
              purposes only. You should not rely solely on JargonScan's output to make legal decisions.
              Always consult a qualified attorney or professional for legal guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">3. Data Handling</h2>
            <p>
              Documents are encrypted during upload using TLS. Uploaded documents are processed by
              our AI analysis engine and permanently deleted from our servers after analysis is complete.
              Scan results are retained in your account for your future reference. We do not use your
              document data for AI model training or any purpose other than generating your scan results.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">4. Payment Terms</h2>
            <p>
              All payments are processed through Stripe. Scans are charged on a per-use basis at the
              rates displayed at the time of purchase. Prices are in US dollars. Refunds are available
              if our system fails to process your document or produces no results. Contact
              support@jargonscan.com for refund requests.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">5. Acceptable Use</h2>
            <p>
              You may only upload documents that you have the legal right to access and share.
              Do not upload documents belonging to others without their consent. Uploading fraudulent
              or illegal content is prohibited and may result in account termination.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">6. Accuracy Disclaimer</h2>
            <p>
              While we strive for accuracy, AI-powered analysis may produce errors, miss issues,
              or generate false positives. JargonScan makes no guarantees regarding the accuracy,
              completeness, or reliability of scan results. Results should be verified by qualified
              professionals before taking action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">7. Limitation of Liability</h2>
            <p>
              JargonScan's liability is limited to the amount you paid for the scan in question.
              We are not liable for any decisions made based on our scan results, any financial
              losses, legal consequences, or other damages arising from the use of our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white">8. Contact</h2>
            <p>
              For questions about these terms, contact us at support@jargonscan.com.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
